### ISSUE TITLE
--lb-pool seen as -lb-pool

### ISSUE THREAD

**Issue by RemiKalbe** [visibilityspots/dockerfile-cloudflared#10]
Hi,

I'm using Kubernetes and when I add the argument --lb-pool I get this message 
```zsh
Incorrect Usage. flag provided but not defined: -lb-pool frontend-lb-pool-a0edd36a
```
It looks like the "--lb-pool" is seen as "-lb-pool"

Is it an issue on your end or is it cloudflared?

**Comment by visibilityspots** [comment]
I think this rather is an issue with how you have to pass such arguments with kubernetes since now the container is trying to interpret this option within the cloudflared binary.

**Comment by visibilityspots** [comment]
Open for a while already. I'll close the issue for now, but can reopen the discussion later when needed.
