### ISSUE TITLE
About once a week been having this issue

### ISSUE THREAD

**Issue by twist2k** [visibilityspots/dockerfile-cloudflared#11]
First off I love the docker container and my DNS privacy thanks you! 

About once a week or so my DNS just takes a dump and I have not been able to figure out what the issue is and after multiple restarts and time passing it just seems to clear sometimes. 

At first I thought it was a cloudflare issue, but I have a buddy that has a similar setup but without the docker and he does not seem to have any problems and according to cloudflared's site they are not having any downtime issues.

I also tried to switch the 1.1.1.1 and whatever there other one is as the primary and it did not seem to make a difference either.

Was thinking it might have something to do with the caching but I was not able to figure out if there is a way to change the cache timeout.

This is what I pull from the logs.

time="2019-07-25T09:35:03Z" level=error msg="failed to connect to an HTTPS backend \"https://1.1.1.1/.well-known/dns-query\"" error="failed to perform an HTTPS request: Post https://1.1.1.1/.well-known/dns-query: net/http: request canceled (Client.Timeout exceeded while awaiting headers)",
time="2019-07-25T09:35:05Z" level=error msg="failed to connect to an HTTPS backend \"https://1.0.0.1/.well-known/dns-query\"" error="failed to perform an HTTPS request: Post https://1.0.0.1/.well-known/dns-query: net/http: request canceled (Client.Timeout exceeded while awaiting headers)",
time="2019-07-25T09:35:05Z" level=error msg="failed to connect to an HTTPS backend \"https://1.1.1.1/.well-known/dns-query\"" error="failed to perform an HTTPS request: Post https://1.1.1.1/.well-known/dns-query: net/http: request canceled (Client.Timeout exceeded while awaiting headers)",
time="2019-07-25T09:35:08Z" level=error msg="failed to connect to an HTTPS backend \"https://1.1.1.1/.well-known/dns-query\"" error="failed to perform an HTTPS request: Post https://1.1.1.1/.well-known/dns-query: net/http: request canceled (Client.Timeout exceeded while awaiting headers)",

Thanks again for this container and hopefully I can figure out this one and only issue I have had.

UPDATE: 7-25-19 4:30PM Pacific

I found this in my googling, but my WAN IP does not change, or has not changed in a couple years.

https://community.cloudflare.com/t/solved-1-1-1-1-over-cloudflared-linux-nonstandard-port-fails-after-some-time/14856

**Comment by visibilityspots** [comment]
That is a weird error I've never seen myself before unfortunately. I think it's better to file an issue on the cloudflared repo itself about this..
