### ISSUE TITLE
Outdated dockerhub images for arm/arm64

### ISSUE THREAD

**Issue by ArXa1L** [visibilityspots/dockerfile-cloudflared#12]
Hi,
Since the 2th of September all Travis CI builds on arm and arm64 architectures have failed with “CRON Fix: credential update” error, while the builds on amd64 architecture were successful.

The last docker image also doesn’t actually work properly, i have noticed the following errors in the logs:
```
time="2019-10-14T17:24:22Z" level=error msg="failed to connect to an HTTPS backend \"https://1.0.0.1/.well-known/dns-query\"" error="failed to perform an HTTPS request: Post https://1.0.0.1/.well-known/dns-query: net/http: request canceled while waiting for connection (Client.Timeout exceeded while awaiting headers)"
```

Please fix the buils.

usefull links:
https://hub.docker.com/r/visibilityspots/cloudflared/tags?page=1&name=arm
https://travis-ci.org/visibilityspots/dockerfile-cloudflared/builds

**Comment by visibilityspots** [comment]
@ArXa1L So upstream fixed the issue my build was encountering using the tunneldns library and the builds are green again. Could you retry?
