### ISSUE TITLE
failed to connect to an HTTPS backend

### ISSUE THREAD

**Issue by woiza** [visibilityspots/dockerfile-cloudflared#15]
Would it be possible to implement the fix in your docker image?

https://github.com/cloudflare/cloudflared/issues/91#issuecomment-596896846

**Comment by julien-vu** [comment]
I think the fix should be done on the cloudflared repo since our dockerfile just pull from it 
[this line](https://github.com/visibilityspots/dockerfile-cloudflared/blob/c371ac578527522da733bfa2fc529b920947e42a/Dockerfile#L9)

**Comment by woiza** [comment]
ok, thanks for the clarification.
