### ISSUE TITLE
No enruta la peticiones

### ISSUE THREAD

**Issue by richardrey** [visibilityspots/dockerfile-cloudflared#17]
Hola buenas tardes

funciona el contenedor a nivel local y acepta las peticiones de los contenedores que se desplieguen en su misma red pero desde otros equipos externos al host donde esta ejecutándose no funciona.

me pueden ayudar por favor

un saludo

**Comment by richardrey** [comment]
Esta es la tabla de enrutamiento que hay:

Proto Recv-Q Send-Q Local Address           Foreign Address         State       PID/Program name    
tcp        0      0 127.0.0.11:38095        0.0.0.0:*               LISTEN      -
tcp        0      0 127.0.0.1:37043         0.0.0.0:*               LISTEN      -
tcp        0      0 10.10.0.2:59112         1.1.1.1:443             ESTABLISHED -
`tcp        0      0 :::5054                 :::*                    LISTEN      -`
udp        0      0 127.0.0.11:51437        0.0.0.0:*                           -
`udp        0      0 :::5054                 :::*               `                 -


los puesto 5054 que funciona perfectamente no es accesible desde otros orígenes, si hago las peticiones de contenedor a contenedor en el mismo host y en la misma red de contenedores funciona, si lo hago desde un host diferente no funciona.

**Comment by visibilityspots** [comment]
could you elaborate how you started the container?

**Comment by richardrey** [comment]
sorry i checked and what happens is that the requests against PiHole are not encrypted but when i make the requests against the cloudflared container they are.

greetings forgive the inconvenience now works correctly.

**Comment by visibilityspots** [comment]
No problem I'm glad you got it figured out and have it up and running!
