### ISSUE TITLE
[question] where can I find the config.yml file ?

### ISSUE THREAD

**Issue by julien-vu** [visibilityspots/dockerfile-cloudflared#18]
Hello, is there a way to edit a config.yml file ? I did not find it in the container

**Comment by visibilityspots** [comment]
Hi, there isn't a config file involved since the parameters are passed through to the run command..

**Comment by nathang21** [comment]
I am trying to enable IPV6, and according to the cloudflare docs/discussions the following line is needed:   
`proxy-dns-address: "::"`

It would be nice if we could pass in a config file, or easily add environment variables somehow. 
This is an example of my desired config.
```
logfile: /var/log/cloudflared.log
proxy-dns: true
proxy-dns-port: 5054
proxy-dns-address: "::"
proxy-dns-upstream:
 - https://1.1.1.2/dns-query
 - https://1.0.0.2/dns-query
```
