### ISSUE TITLE
Parameterize the upstream IPs. 1.1.1.1 and 1.0.0.1

### ISSUE THREAD

**Issue by davidcastellani** [visibilityspots/dockerfile-cloudflared#2]
On my AT&T network, I cannot talk to 1.1.1.1 but I can talk to 1.0.0.1.

Would it be possible to allow environmental variables to be used to pick which upstream DNS server is used so the order could be changed?

**Comment by visibilityspots** [comment]
@davidcastellani good point, I configured the upstream DNS servers as ENV parameters with default values of 1.1.1.1 and 1.0.0.1 (https://github.com/visibilityspots/dockerfile-cloudflared/commit/db59c824176714b144f364c374f67fcce88d3be2).

So you can now easily override those by giving an -e ENV param during the docker run command as described in the [README](https://github.com/visibilityspots/dockerfile-cloudflared#custom-upstream-dns).

Let me know if this solves your issue.

**Comment by davidcastellani** [comment]
Perfect! Thank you.
