### ISSUE TITLE
Updated docker images not being pushed due to travis failures

### ISSUE THREAD

**Issue by nathang21** [visibilityspots/dockerfile-cloudflared#25]
In addition to #24 (which is still giving the same error) it seems there are couple errors within the build output:
https://travis-ci.org/github/visibilityspots/dockerfile-cloudflared/jobs/737883452

1. The command '/bin/sh -c setcap CAP_NET_BIND_SERVICE+eip /usr/local/bin/cloudflared' returned a non-zero code: 127
The command "docker build -t visibilityspots/cloudflared:$TAG --build-arg ARCH="$ARCH" --build-arg GOARCH="$GOARCH" --build-arg GOARM="$GOARM" ./" exited with 127.

2. Error: Cannot perform an interactive login from a non TTY device
The command "echo "$DOCKER_PASSWORD" | docker login --username visibilityspots --password-stdin" exited with 1.

3. denied: requested access to the resource is denied
unauthorized: authentication required
The command "docker push visibilityspots/cloudflared:$TAG" exited with 1.

Error 3 is expected because of 2, no clue what the impact of 1 is will need to research.

**Comment by nathang21** [comment]
Update: It seems like only the `arm` build is failing, but the way the pipeline is setup the whole thing returns a failure which just means the `latest` tag isn't added, but the dedicated architecture tags can still be pulled. 
https://hub.docker.com/r/visibilityspots/cloudflared/tags
![image](https://user-images.githubusercontent.com/7875110/96885213-3df2a100-1437-11eb-80a1-0ae8c0c4bd5a.png)

**Comment by nathang21** [comment]
@visibilityspots is there something special about the `-edge` variant of `multiarch/alpine:${ARCH}-edge` image you are using?

I think the root cause is the upstream image for [multiarch/alpine:armhf-edge](https://hub.docker.com/layers/multiarch/alpine/armhf-edge/images/sha256-2f3951de7e7f8e923b5e0f6ff59e79dae9b30b479fea6a7fd19748ad8cc873e5?context=explore) also started failing 3 months ago.

Since they are almost identical in size, switching the tag to [multiarch/alpine:armhf-latest-stable](https://hub.docker.com/layers/multiarch/alpine/armhf-latest-stable/images/sha256-a004f2ea16897dcbe985482cdc2705a07211e50b592082eda49a2dda7570b583?context=explore) would solve this problem I think.

We could make an exception for `arm` but that would make the Dockerfile a bit more messy, might be easier to just change them all to `-latest-stable`.

Will send a PR let me know what you think.

**Comment by nathang21** [comment]
Looks like edge is literally the bleeding edge and unstable.
https://wiki.alpinelinux.org/wiki/Edge

Following this, it should be simple to switch. 
https://wiki.alpinelinux.org/wiki/Upgrading_Alpine#Upgrading_to_latest_release

**Comment by visibilityspots** [comment]
Hi @nathang21 thanks for pointing some things out, using latest-stable is definitely a better choice! I've pushed this change already. 
About the docker login, I accepted your --username change but that's not the issue. The tags are pushed without any issue. But the failure of the armhf job is blocking the update of the latest matrix. 

Which isn't a good thing for sure, I do hope the latest-stable change would solve this issue. Else I need to investigate some time how to solve this..

I had a similar issue in the past which got resolved upstream luckily but it seems to be stuck this time :(

**Comment by visibilityspots** [comment]
@nathang21 thanks a lot for the time you've putted into investigating this issue. As you can see using the latest-stable did fix the build and now the latest matrix also got updated!

Closing this issue as I think it's resolved now?

**Comment by nathang21** [comment]
Ah you beat me to it thanks for that, everything looks green now indeed will test locally as well!
