### ISSUE TITLE
Use official cloudflared releases

### ISSUE THREAD

**Issue by nathang21** [visibilityspots/dockerfile-cloudflared#26]
I don't think we necessarily want to pull the latest master branch of cloudflared. It looks like they are now tagging official releases
https://github.com/cloudflare/cloudflared/releases

When running `cloudflared --version` via dgoss or docker run the version that is always returned is:
`cloudflared version DEV (built unknown)`.

However when I download the latest release myself I get the following: 
`cloudflared version 2020.10.2 (built 2020-10-21-1908 UTC)`

I can send a PR eventually, not a high priority. I think the DEV version still includes all the latest changes, but I haven't actually confirmed this (yet).

**Comment by visibilityspots** [comment]
@nathang21 that would be a great improvement indeed. Next to the latest changes I also want to get it stable. Can't complain about issues I got over the last couple of years but it seems that a this container image got some traction over time and it would be a huge dissapointment for many (including myself) when a new automated update breaks stuff..

**Comment by visibilityspots** [comment]
fixed by #36
