### ISSUE TITLE
Custom DNS server are not respected at runtime

### ISSUE THREAD

**Issue by nathang21** [visibilityspots/dockerfile-cloudflared#28]
Default `$DNS` values are currently hard coded into the docker build, and only the `$UPSTREAM` variables are set dynamically at runtime.

**Comment by qauff** [comment]
I'm seeing the same issues.

**Comment by visibilityspots** [comment]
valid point, somehow I'm wondering if it wouldn't be a better idea to get rid of the DNS{1|2} parameters. They aren't used at runtime. And maybe a bit confusing regarding the docker run --dns option.

When defaulting upstream{1|2} towards https://1.1.1.1/dns-query and https://1.0.0.1/dns-query the cloudflared DNS services one can always overrule the DNS services by using the upstream environment variables
