### ISSUE TITLE
Misleading image description in docker-hub

### ISSUE THREAD

**Issue by dzonatan** [visibilityspots/dockerfile-cloudflared#32]
It's a bit odd that `dockerfile-cloudflared` image in docker hub contains a description not its own, but from `dockerfile-domain-watcher`: 
https://hub.docker.com/r/visibilityspots/cloudflared

![image](https://user-images.githubusercontent.com/5166666/108602115-eba39b80-73a8-11eb-93ab-4c3086648ceb.png)

**Comment by visibilityspots** [comment]
wow seems I miscopied a README file over there :facepalm: thanks for creating an issue for this one, I placed the correct description on docker hub now following the one from github!
