### ISSUE TITLE
Status of project?

### ISSUE THREAD

**Issue by calderonth** [visibilityspots/dockerfile-cloudflared#50]
Hi there,

Are you still planning on maintaining this?
Seems like there has not been any update to the Docker image on DockerHub in a while.

Thanks!

**Comment by visibilityspots** [comment]
there you go https://github.com/visibilityspots/dockerfile-cloudflared/commit/9a2f9c418bac1a190befadf43b6ed43d8d77eced

**Comment by calderonth** [comment]
Hey there, thanks for that.
However, I think that's bumped to a newer version of cloudflared but this hasn't released a new Docker image for it on DockerHub?

**Comment by visibilityspots** [comment]
@calderonth running latest you should have the latest cloudflared release available?
