### ISSUE TITLE
About mount local volume

### ISSUE THREAD

**Issue by taimadoCE** [visibilityspots/dockerfile-cloudflared#53]
Is it possible to map/mount locally the /cloudflared directory to don't lose the tunnel json and de config.yml after a container update?

**Comment by visibilityspots** [comment]
Hi @taimadoCE if you create a [mount](https://docs.docker.com/storage/bind-mounts/) you could achieve that behavior. Although it could be more efficient to create extra configuration parameters for the needed config parameters instead?

Could you elaborate more on which parameters you want to modify?

**Comment by taimadoCE** [comment]
> 
hi again. I've been triying to mount the /home/cloudflared/.cloudflared locally and the only thing I get is an error.
Could you put an example that works?
I'm triying with something like this:
-v /mylocation/cloudflared:/home/cloudflared/.cloudflared

**Comment by taimadoCE** [comment]
> Hi @taimadoCE if you create a [mount](https://docs.docker.com/storage/bind-mounts/) you could achieve that behavior. Although it could be more efficient to create extra configuration parameters for the needed config parameters instead?
> 
> Could you elaborate more on which parameters you want to modify?

Hi again. I've been triying to mount the /home/cloudflared/.cloudflared locally and the only thing I get is an error.
Could you put an example that works?
I'm triying with something like this:
-v /mylocation/cloudflared:/home/cloudflared/.cloudflared

**Comment by visibilityspots** [comment]
Hi 

I just tried to mount a cloudflared directory from my local system towards the container with a .cloudflared file with some foobar text and the container is starting well:

`docker run --rm -v /home/jan/downloads/cloudflared:/home/cloudflared/ visibilityspots/cloudflared`

Which is the error message you stumble into?

**Comment by taimadoCE** [comment]
> Hi
> 
> I just tried to mount a cloudflared directory from my local system towards the container with a .cloudflared file with some foobar text and the container is starting well:
> 
> `docker run --rm -v /home/jan/downloads/cloudflared:/home/cloudflared/ visibilityspots/cloudflared`
> 
> Which is the error message you stumble into?

I get to mount the volume when I do the docker run but after that when I try to login in cloudflared i get this:

![imagen](https://user-images.githubusercontent.com/57089805/209294925-541c1529-72f1-4e5e-bf53-39442c587015.png)

**Comment by visibilityspots** [comment]
@taimadoCE is this still an issue?
