### ISSUE TITLE
Port mismatch against the dockerfile hosted on dockerHub (README outdated?) 

### ISSUE THREAD

**Issue by altmas5** [visibilityspots/dockerfile-cloudflared#8]
I was running some tests using the image hosted on DockerHub and found out it runs cloudflared on port 54 instead of 5054. On the README port 5054 is stated as the default.
Which of the 2 should be the expected behavior?

**Comment by visibilityspots** [comment]
Are you using the latest version of docker hub?

**Comment by visibilityspots** [comment]
I saw where it went wrong, a few months ago I changed the latest tag to amd64. Travis stopped pushing to latest tag so that explains why that image was outdated with the port change!

Thanks for pointing that out.

**Comment by altmas5** [comment]
You're Welcome!
