### ISSUE TITLE
dockerhub image possibly out of date

### ISSUE THREAD

**Issue by NEXUS2345** [visibilityspots/dockerfile-cloudflared#9]
When trying to run this image using docker compose, I am getting consistent issues with it being unable to find the manifests which I know you already created in #5. When I click on the dockerfile tab in the hub it shows a very outdated version of the file, so I was wondering if it wasn't updating correctly for some reason?

Also, would you be able to add the aarch64 tag into the manifest so that this can be run on Raspberry Pi?

**Comment by visibilityspots** [comment]
The Dockerfile got only updated when using the docker hub automated build scripts but I skipped those and use travis instead.
I'll trigger a manual build to update the dockerfile for now.
For the raspberry pi you could use the arm64 tag?

**Comment by NEXUS2345** [comment]
Thanks for the quick response. Unfortunately, on some distros for Raspberry Pi, the architecture is classified as aarch64 due to weirdness in the ecosystem regarding Apple vs everyone else (as it always is). So for example, while Raspbian might use arm64, Fedora and OpenSUSE use aarch64.

**Comment by visibilityspots** [comment]
I gave it a try to add the aarch64 but seems that I'm missing something: https://travis-ci.org/visibilityspots/dockerfile-cloudflared/jobs/517155951..
